import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import { Inter as FontSans } from "next/font/google"

import { SessionProvider } from 'next-auth/react';
import { auth } from "./auth";
import { cn } from "@/lib/utils"
import NavBar from "./components/NavBar";
 
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
{
  const session = await auth()
  return (
    <html lang="en">
      <SessionProvider session={session}>
      <body className={cn(
          "min-h-screen bg-background font-sans antialiased overflow-hidden",
          fontSans.variable
        )}>
          <NavBar></NavBar>
          <main>
            {children}
          </main>
          </body>
      </SessionProvider>
    </html>
  );
}
